---
driver:
  name: vagrant

provisioner:
  http_proxy: http://www-proxy-idc.in.oracle.com:80
  https_proxy: http://www-proxy-idc.in.oracle.com:80
  chef_license: true
  chef_license: "accept"
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec
  chef_license: true
  chef_license: "accept"

platforms:
#  - name: ubuntu-16.04
  - name: centos-7

suites:
  - name: default
    run_list:
      - recipe[git_cookbook::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
